apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gwanho-latest
labels:
- includeTemplates: true
  pairs:
    app.kubernetes.io/part-of: gwanho-backend
resources:
- pikachu
- gangar
- charizard
- blastoise
images:
- name: gwanho-backend/blastoise
  newName: asdf
  newTag: docker-v1-02
- name: gwanho-backend/charizard
  newName: asdf
  newTag: docker-v1-02
- name: gwanho-backend/gangar
  newName: asdf
  newTag: "12345"
- name: gwanho-backend/pikachu
  newName: asdf
  newTag: docker-v1-02
