name: do-smt-after-commit-on-main
on:
  push:
    branches:
      - main

jobs:
  edit-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TRIGGER_COMMIT_ON_MAIN }} # 여기 PAT 토큰을 사용해야 github bot이 main에 커밋을 할 수 있음

      - name: Do something 
        run: |
          echo "Print BOT.md to see it has the most recent changes"
          cat BOT.md