name: do-smt-after-commit-on-main
on:
  push:
    branches:
      - main

jobs:
  do-something-after-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TRIGGER_COMMIT_ON_MAIN }} # 여기 PAT 토큰을 사용해야 github bot이 main에 커밋을 할 수 있음

      - name: Do something 
        id: do-something
        run: |
          echo "Print BOT.md to see it has the most recent changes"
          cat BOT.md
          echo "did_something=true" >> $GITHUB_OUTPUT

      - name: Check it did something
        id: check-did-something
        if: steps.do-something.outputs.did_something == 'false'
        run: |
          echo "It did something, so we can proceed with the commit."

      - name: Check if it did not something
        if: steps.check-did-something.outcome == 'success'
        run: |
          echo "It did do something, so we will proceed with the commit."

      - name: Check if it skipped
        if: steps.check-did-something.outcome == 'skipped'
        run: |
          echo "It did not do something, so we will skip the commit."

      - name: Print github.sha
        run: |
          echo "github.sha: ${{ github.sha }}"
          echo "-----------------------------------"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.workflow: ${{ github.workflow }}"
          


