name: do-smt-after-commit-on-main
on:
  push:
    branches:
      - main

jobs:
  edit-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TRIGGER_COMMIT_ON_MAIN }} # 여기 PAT 토큰을 사용해야 github bot이 main에 커밋을 할 수 있음

      - name: Do something 
        id: do-something
        run: |
          echo "Print BOT.md to see it has the most recent changes"
          cat BOT.md
          echo "did_something=true" >> $GITHUB_OUTPUT

      - name: diff --quiet
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        run: |
          if git diff --quiet; then
            echo "Skip other steps"
            gh run cancel $ {{ github.run_id }}
            gh run watch ${{ github.run_id }} 
          fi

      - name: Check it did something
        if: steps.do-something.outputs.did_something == 'true'
        run: |
          echo "It did something, so we can proceed with the commit."


