name: format test
on:
  workflow_dispatch:
    inputs:
      var1:
        description: '바깥 format에서 출력될 값'
        required: true
        default: 'var1'
      var2:
        description: '안쪽 format에서 출력될 값'
        required: true
        default: 'var2'


env:
  OUTER_VAR: ${{ github.event.inputs.var1 }}
  INNER_VAR: ${{ github.event.inputs.var2 }}

jobs:
  make-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make output
        run: |
          echo "output1=한글깨지나?" >> "$GITHUB_OUTPUT"
          echo "output2=English?" >> "$GITHUB_OUTPUT"
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: a format inside a format
        run: |
          echo "${{ format('바깥 format 값: {0}, {1}', env.OUTER_VAR, format('안쪽 format 값: {0} Output1 값: {1}, Output2 값: {2}', env.INNER_VAR, steps.make-output.outputs.output1, steps.make-output.outputs.output2)) }}"