on:
  workflow_dispatch:
    inputs:
      word:
        description: '단어를 입력하세요, 비교 대상 단어는 Hello입니다.'
        required: true
        default: 'Hell'

env:
  WORD: ${{ github.event.inputs.word }}

jobs:
  start_with_check1:
    runs-on: ubuntu-latest
    steps:
      - name: Check the word starts with 'Hello'
        id: check-word
        if: ${{ env.WORD && !startsWith(env.WORD, 'Hello') }} 
        run: |
          echo "The word does not start with 'Hello'."

  start_with_check2:
    runs-on: ubuntu-latest
    steps:
      - name: Check the word starts with 'Hello'
        id: check-word
        if: ${{ env.WORD }} && !startsWith(${{ env.WORD }}, 'Hello') 
        run: |
          echo "The word does not start with 'Hello'."
