on:
  workflow_dispatch:
    inputs:
      word:
        description: '단어를 입력하세요, 비교 대상 단어는 Hello입니다.'
        required: true
        default: 'Hell'


jobs:

  start_with_check_current:
    runs-on: ubuntu-latest
    steps:
      - name: Check the word starts with 'Hello'
        id: check-word
        if:  inputs.word && !startsWith(inputs.word, 'Hello') 
        run: |
          echo "The word does not start with 'Hello'."

  start_with_check_fixed:
    runs-on: ubuntu-latest
    steps:
      - name: Check the word starts with 'Hello'
        id: check-word
        if: ${{ inputs.word && !startsWith(inputs.word, 'Hello') }} 
        run: |
          echo "The word does not start with 'Hello'."



    start_with_check_fixed2:
      runs-on: ubuntu-latest
      steps:
        - name: Check the word starts with 'Hello'
          id: check-word
          if:  inputs.word && !(startsWith(inputs.word, 'Hello')) 
          run: |
            echo "The word does not start with 'Hello'."
