name: strategy에 fromJSON, join 사용 테스트

on:
    workflow_dispatch:
        inputs:
            servers: 
                description: "서버 리스트"
                required: true
                default: "server1,server2,server3"

jobs:
    make-output:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.make-output.outputs.servers }}
        steps:
            - id: make-output
              run: |
                SERVERS=""
                IFS=',' read -ra SERVERS_ARRAY <<< "${{ inputs.servers }}"
                for server in "${SERVERS_ARRAY[@]}"; do
                    SERVERS="$SERVERS,\""$server"\""
                done
                
                SERVERS=$(echo $SERVERS | sed 's/^,//')
                echo "servers={\"env\":[$SERVERS]}" >> $GITHUB_OUTPUT

    print-output:
        runs-on: ubuntu-latest
        needs: make-output
        steps:
            - name: print
              run: |
                echo "SERVERS=$SERVERS"

    test-output-exists-1:
        runs-on: ubuntu-latest
        needs: make-output
        if: ${{ needs.make-output.outputs.matrix }}
        strategy:
            matrix:
                server: ${{ fromJSON(needs.make-output.outputs.matrix) }}
        steps:
            - name: print
              run: |
                echo "server: ${{ matrix.server }}"
                echo "server.env: ${{ matrix.server.env }}"

    test-output-exists-2:
        runs-on: ubuntu-latest
        needs: make-output
        if: ${{ fromJSON(needs.make-output.outputs.matrix).env != '' }}
        strategy:
            matrix:
                server: ${{ fromJSON(needs.make-output.outputs.matrix) }}
        steps:
            - name: print
              run: |
                echo "server: ${{ matrix.server }}"
                echo "server.env: ${{ matrix.server.env }}"