name: "Manual Slack Fail Notification Trigger"

on:
  workflow_dispatch:
    inputs:
      message:
        description: "메시지"
        required: false
      channel_id:
        description: "채널 ID"
        required: true
      thread_ts:
        description: "스레드 타임스탬프"
        required: true

jobs:
  Inputs:
    - name: Output inputs
      run: |
        echo "Inputs:"
        echo "message=${{ github.event.inputs.message }}" >> "$GITHUB_OUTPUT"
        echo "channel_id=${{ github.event.inputs.channel_id }}" >> "$GITHUB_OUTPUT"
        echo "thread_ts=${{ github.event.inputs.thread_ts }}" >> "$GITHUB_OUTPUT"
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Trigger trigger-slack-notify-fail.yaml
        uses: ./.github/workflows/trigger-slack-notify-fail.yaml
        with:
          message: ${{ github.event.inputs.message }}
          channel_id: ${{ github.event.inputs.channel_id }}
          thread_ts: ${{ github.event.inputs.thread_ts }}
